### ISSUE TITLE
Many Zeros in the middle of xid running on Macos

### ISSUE THREAD

**Issue by inebritov** [Yortw/Xid.Net#1]
I use the `Xid.NewXid()` generation method and it gives me result with zeros in the middle. I was curious and checked internals of the library, so it seems that function generating for Machine ID (B5-B7) return small number. Also, Process ID (B8-B9) in Docker is less than 255, so I have noticeable amount of zeros in the middle of the Xid:

```
  Xid.NewXid()
  {cq6jk4jp000000bu30mg}
    _B1: 102
    _B2: 141
    _B3: 58
    _B4: 18
    _B5: 121
    _B6: 0
    _B7: 0
    _B8: 0
    _B9: 1
    _B10: 126
    _B11: 24
    _B12: 45

  {cq6kkkmg000008d6gp90}
    _B1: 102
    _B2: 141
    _B3: 74
    _B4: 82
    _B5: 208
    _B6: 0
    _B7: 0
    _B8: 0
    _B9: 33
    _B10: 166
    _B11: 134
    _B12: 83

```

On the host machine (.net installed in the system) it looks better, but it still has zero-bytes:

```
 {cq6md0460004fnfkqhpg}
    _B1: 102
    _B2: 141
    _B3: 102
    _B4: 128
    _B5: 134
    _B6: 0
    _B7: 0
    _B8: 71
    _B9: 221
    _B10: 244
    _B11: 212
    _B12: 115
    
{cq6md9460004fnfkqhq0}
    _B1: 102
    _B2: 141
    _B3: 102
    _B4: 164
    _B5: 134
    _B6: 0
    _B7: 0
    _B8: 71
    _B9: 221
    _B10: 244
    _B11: 212
    _B12: 117
```

Environment:

- MacBook with m2
- Docker Compose
- DotNet Core 8

**Comment by inebritov** [comment]
Reproduced in Docker on Linux

**Comment by inebritov** [comment]
I’ve checked the code with the debugger, and it looks like the library has a slight difference from the original. [Here](https://github.com/Yortw/Xid.Net/blob/ff46b19bca1/src/Xid.Shared/Xid.cs#L240), in the machine ID generation, we calculate the sum of the hash, but in the [original library](https://github.com/rs/xid/blob/9d8d29f19/id.go#L119), the hash bytes are used raw. So I made a pull request to fix that: https://github.com/Yortw/Xid.Net/pull/2

I'm not sure about performance, as the [last build](https://ci.appveyor.com/project/Yortw/xid-net/builds/50255162) shows the Error Message: Test 'Xid_New_Performance' exceeded execution timeout period. I can't figure out what's wrong and I need assistance with that.

**Comment by Yortw** [comment]
I have published a 2.0.1-beta version of the package to nuget, if you'd like to try it and let me know if it works. The tests all pass, benchmarks run and the generated values look good to me.

**Comment by inebritov** [comment]
Yep, tested it, works well:
```csharp
using XidNet;
Console.WriteLine(Xid.NewXid());
Console.WriteLine(Xid.NewXid());
Console.WriteLine(Xid.NewXid());
Console.WriteLine(Xid.NewXid());
```
Output:
```
cs1titrb3p24shn4h8qg
cs1titrb3p24shn4h8r0
cs1titrb3p24shn4h8rg
cs1titrb3p24shn4h8s0
```

**Comment by Yortw** [comment]
Thanks for the PR and your assistance with testing. New, non-beta, package published now.
